#!/bin/bash
                                        #### BATCH_SYSTEM=SLURM ####
########################################################################
#SBATCH --account smr_prod
#SBATCH --partition dcgp_usr_prod
#SBATCH --job-name  ICONREMAP_%expid%
#SBATCH --output=end_LL_%filesuffix%
#SBATCH --error=err_LL_%filesuffix%
#SBATCH --time=02:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --export=ALL
########################################################################
#
echo
echo "###INT2LM: Job-ID : $SLURM_JOB_ID"
echo "###INT2LM: Host   : $(hostname)"
echo
#
########################################################################
BINARY=%binary%
########################################################################
### Job specific:
module purge
module load profile/meteo
module load intel-oneapi-compilers/2023.2.1
module load intel-oneapi-mpi/2021.10.0
module load intel-oneapi-mkl/2023.2.0
module load libszip/2.1.1--oneapi--2023.2.0
module load zlib/1.3--gcc--12.2.0
module load zlib-ng/2.1.4--oneapi--2023.2.0
module load zstd/1.5.5--oneapi--2023.2.0-7fv2v7i
module load libaec/1.0.6--oneapi--2023.2.0-ohnhau5
module load bzip2/1.0.8--oneapi--2023.2.0-775effc
module load lz4/1.9.4--oneapi--2023.2.0-whwwyrc
module load snappy/1.1.10--oneapi--2023.2.0-ta4wo5m
module load c-blosc/1.21.5--oneapi--2023.2.0-e7safqx
module load pkgconf/1.9.5-gr2lx34
module load hdf5/1.14.3--intel-oneapi-mpi--2021.10.0--oneapi--2023.2.0
module load parallel-netcdf/1.12.3--intel-oneapi-mpi--2021.10.0--oneapi--2023.2.0
module load netcdf-c/4.9.2--intel-oneapi-mpi--2021.10.0--oneapi--2023.2.0
module load netcdf-fortran/4.6.1--intel-oneapi-mpi--2021.10.0--oneapi--2023.2.0
module load openjpeg/2.3.1--oneapi--2023.2.0-63yr4zj
module load eccodes/2.33.0--intel-oneapi-mpi--2021.10.0--oneapi--2023.2.0
#export ECCODES_DEFINITION_PATH="/leonardo_scratch/fast/DE360_GLORI/definitions/2.32.0-2/definitions.edzw":"/leonardo_scratch/fast/DE360_GLORI/definitions/2.32.0-2/definitions"
export ECCODES_DEFINITION_PATH="/leonardo_work/smr_prod/lami/data/definitions/definitions.cineca-2.21.0":"/leonardo_work/smr_prod/lami/data/definitions/definitions.edzw-2.21.0-1"
export NMPI_FPE_ENABLE=(DIV,FOF,INV)
export NMPI_EXPORT=" NMPI_FPE_ENABLE NMPI_PROGINF NMPI_TRACEBACK"
########################################################################
###  MODEL: remap  ###
for ensmem in $(seq %ensmem_start% %ensmem_end%); do
  ensmem3=$(printf "%.3d" $ensmem)
  if [ "$ensmem" -eq 0 ]; then
    message="deterministic run"
    cd $SLURM_SUBMIT_DIR/det
  else
    message="ensemble member $ensmem (of %ensmem_end%)"
    cd $SLURM_SUBMIT_DIR/mem${ensmem3}
  fi
  echo "in rundir: $(pwd)"
  echo
  ls -lL $BINARY
  rm -f READY
  export MPIRUN_OPTIONS="--bind-to core --map-by core -report-bindings"
  echo
  echo "###INT2LM: calling binary for $message at $(date)"
  echo
  for nml in %nml_basename%_* ; do
    echo
    echo "------------------------------------------------------------------------"
    echo "mpirun -v -n ${SLURM_NTASKS} ${MPIRUN_OPTION} ${BINARY} --remap_nml $nml"
    echo "------------------------------------------------------------------------"
    mpirun -v -n ${SLURM_NTASKS} ${MPIRUN_OPTION} ${BINARY} -q --remap_nml $nml
    rc=$?
    echo "------------------------------------------------------------------------"
    echo
    [ $rc -ne 0 ] && break
  done
  echo "###INT2LM: done with binary for $message at $(date)"
  echo
  if [ $rc -ne 0 ]; then
    echo; echo >&2
    echo "mpirun failed: rc=$rc" >&2
    echo "mpirun failed: rc=$rc"
    echo; echo >&2
    exit $rc
  fi
  date > READY
done
