#!/bin/sh

case "$HPC_SYSTEM" in
    galileo ) # Cineca HPC galileo
# for galileo remove /gpfs/work from LD_LIBRAR_PATH, move installation
# from $WORK to /gpfs/meteo and replace $WORK with $WORKDIR_BASE
	export LD_LIBRARY_PATH=/cineca/prod/opt/libraries/qt/5.9/gnu--6.1.0/lib:/cineca/prod/opt/compilers/gnu/6.1.0/none/lib64
	export PATH=$WORKDIR_BASE/srcgnu/install/bin:/cineca/prod/opt/libraries/qt/5.9/gnu--6.1.0/bin:/cineca/prod/opt/compilers/gnu/6.1.0/none/bin:/cineca/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/pbs/bin:/galileo/home/usera07smr/a07smr03/.local/bin:/galileo/home/usera07smr/a07smr03/bin
	export PYTHONPATH=$WORKDIR_BASE/srcgnu/install/lib/python2.7/site-packages
	;;

meucci ) # Cineca HPC meucci
	export LD_LIBRARY_PATH=/cineca/prod/opt/libraries/qt/5.9/gnu--6.1.0/lib:/meucci/prod/build/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.1.0-6s544hqxrrbq5nefhnmrravkntz25z34/lib64:/meucci/prod/build/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.1.0-6s544hqxrrbq5nefhnmrravkntz25z34/lib
	export PATH=$WORKDIR_BASE/srcgnu/install/bin:/cineca/prod/opt/libraries/qt/5.9/gnu--6.1.0/bin:/meucci/prod/build/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.1.0-6s544hqxrrbq5nefhnmrravkntz25z34/bin:/cineca/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/meucci/home/usera07smr/a07smr03/.local/bin:/meucci/home/usera07smr/a07smr03/bin
	export PYTHONPATH=$WORKDIR_BASE/srcgnu/install/lib/python2.7/site-packages
	;;
g100 | leonardo ) # Cineca HPC Galileo 100
	export WORKDIR_BASE=/leonardo_work/DE360_GLORI/smr_prod/scenarios/scenario_3
	export PATH=/leonardo_work/smr_prod/lami/srcgnu/install/bin:$PATH
	export PYTHONPATH=/leonardo_work/smr_prod/lami/srcgnu/install/lib/python3.6/site-packages
	;;
esac

exec "$@"
