#!/bin/bash
                      #### BATCH_SYSTEM=SLURM ####
########################################################################
#SBATCH --account smr_prod
#SBATCH --partition dcgp_usr_prod
#SBATCH --job-name CO_ICON_%expid%
#SBATCH --qos=normal
#SBATCH --output=end_LL
#SBATCH --error=err_LL
#SBATCH --nodes=6
#SBATCH --ntasks-per-node=112
#SBATCH --sockets-per-node=2
##SBATCH --cores-per-socket=56
#SBATCH --ntasks-per-socket=56
#SBATCH --cpus-per-task=1
#SBATCH --ntasks-per-core=1
##SBATCH --mem=360G
#SBATCH --time=00:30:00
#SBATCH --export=ALL,BINARY=%binary%
########################################################################
#
module purge
# load correct modules 
#export ECCODES_DEFINITION_PATH="/leonardo_scratch/fast/DE360_GLORI/definitions/2.32.0-2/definitions"
#module load profile/meteo
#module load eccodes/2.25.0--gcc--11.3.0
#module load hdf5
#module load netcdf-c
#module load netcdf-fortran
#module load profile/meteo
#module load nvhpc/23.1
#module load openmpi/4.1.4--nvhpc--23.1-cuda-11.8
#module load eccodes/2.25.0--nvhpc--23.1
#module load cdo/2.1.0--gcc--11.3.0
# module load openmpi/4.1.6--gcc--12.2.0
#module load intel-oneapi-mpi
#module load eccodes/2.25.0--gcc--11.3.0
##module load intel-oneapi-compilers/2023.2.1                             
##module load intel-oneapi-mpi/2021.10.0   
##module load pkgconf/1.9.5-gr2lx34                                       
##module load zlib-ng/2.1.4--oneapi--2023.2.0                             
##module load hdf5/1.14.3--intel-oneapi-mpi--2021.10.0--oneapi--2023.2.0
##LD_LIBRARY_PATH=/leonardo_work/smr_prod/lami/srcintel/install/lib:$LD_LIBRARY_PATH
#export ECCODES_DEFINITION_PATH="/leonardo_scratch/fast/DE360_GLORI/definitions/2.32.0-2/definitions.edzw":"/leonardo_scratch/fast/DE360_GLORI/definitions/2.32.0-2/definitions"
#export ECCODES_DEFINITION_PATH="/leonardo_work/smr_prod/lami/data/definitions/definitions.edzw-2.25.0-1":"/leonardo/prod/spack/03/install/0.19/linux-rhel8-icelake/nvhpc-23.1/eccodes-2.25.0-mtgxissefymnkvp3dklixecnwviaxusa/lib64/definitions"
##ECCODES_DEFINITIONS_BASE=$WORKDIR_BASE/data/definitions/definitions.cineca-2.21.0/definitions
##ECCODES_DEFINITIONS_DWD=$WORKDIR_BASE/data/definitions/definitions.edzw-2.21.0-1
##ECCODES_DEFINITION_PATH=$ECCODES_DEFINITIONS_DWD:$ECCODES_DEFINITIONS_BASE
##GRIB_API_EDZW=/leonardo_work/smr_prod/lami/grib_api_edzw
##export GRIB_DEFINITION_PATH=$GRIB_API_EDZW/1.16.0/definitions.cnmc:$GRIB_API_EDZW/1.16.0/definitions
##export PATH="/leonardo_work/DE360_GLORI/spack_env/install/linux-rhel8-icelake/nvhpc-23.1/eccodes-2.32.0-uvqgacgswurbbpjrl6wxocgevjs5mqxk/bin":$PATH
##export PATH="/leonardo_work/DE360_GLORI/spack_env/install/linux-rhel8-icelake/nvhpc-23.1/netcdf-c-4.9.2-2tw6sc6pyqnex6fp466os3luysxivtty/bin":$PATH
##export PATH="/leonardo_work/DE360_GLORI/spack_env/install/linux-rhel8-icelake/nvhpc-23.1/hdf5-1.14.3-o4ctspbmy2t5wnqg35lnzcfvbqugivjo/bin":$PATH
##export PATH="/leonardo/prod/spack/03/install/0.19/linux-rhel8-icelake/nvhpc-23.1/openmpi-4.1.4-6ek2oqarjw755glr5papxirjmamqwvgd/bin":$PATH
#export LD_LIBRARY_PATH="/leonardo/prod/spack/05/install/0.21/linux-rhel8-icelake/gcc-8.5.0/intel-oneapi-mpi-2021.10.0-6ff7efudnkj4xa7o4j67mxatygwzfwqc/mpi/2021.10.0/lib/release/"
#export LD_LIBRARY_PATH="/leonardo/prod/spack/03/install/0.19/linux-rhel8-icelake/nvhpc-23.1/openmpi-4.1.4-6ek2oqarjw755glr5papxirjmamqwvgd/lib":$LD_LIBRARY_PATH
#export LIBRARY_PATH="/leonardo/prod/spack/03/install/0.19/linux-rhel8-icelake/nvhpc-23.1/openmpi-4.1.4-6ek2oqarjw755glr5papxirjmamqwvgd/lib":$LIBRARY_PATH
module load intel-oneapi-compilers/2023.2.1                             
module load intel-oneapi-mpi/2021.10.0   
module load pkgconf/1.9.5-gr2lx34                                       
module load zlib-ng/2.1.4--oneapi--2023.2.0                             
module load hdf5/1.14.3--intel-oneapi-mpi--2021.10.0--oneapi--2023.2.0
LD_LIBRARY_PATH=/leonardo_work/smr_prod/lami/srcintel/install/lib:$LD_LIBRARY_PATH
GRIB_API_EDZW=/leonardo_work/smr_prod/lami/grib_api_edzw
export GRIB_DEFINITION_PATH=$GRIB_API_EDZW/1.16.0/definitions.cnmc:$GRIB_API_EDZW/1.16.0/definitions
export GRIB_SAMPLES_PATH=$GRIB_API_EDZW/1.16.0/samples
echo "###CORE: Job-ID : $SLURM_JOB_ID"
echo "###CORE: Host   : $(hostname)"
echo
#
echo "Loaded modules:"
echo "==============="
echo $( module list )
echo
echo "LD_LIBRARY_PATH:"
echo "================"
echo ${LD_LIBRARY_PATH}
echo
echo "SLURM environment variables:"
echo "============================"
echo "SLURM_JOB_NODELIST   = ${SLURM_JOB_NODELIST}"
echo "SLURM_JOB_NUM_NODES  = ${SLURM_JOB_NUM_NODES}"
echo "SLURM_TASKS_PER_NODE = ${SLURM_TASKS_PER_NODE}"
echo "SLURM_CPUS_PER_TASK  = ${SLURM_CPUS_PER_TASK}"
echo "SLURM_CPUS_ON_NODE   = ${SLURM_CPUS_ON_NODE}"
echo "SLURM_NTASKS         = ${SLURM_NTASKS}"
echo
########################################################################

NODES=%nodes%
HYPER=%hyperthreads%
########################################################################
export OMP_NUM_THREADS=${OMP_NUM_THREADS:-1}
export NUM_CORES=${SLURM_NTASKS}*${SLURM_CPUS_PER_TASK}
echo "${BINARY} running on ${NUM_CORES} cores with ${SLURM_NTASKS} MPI-tasks and ${OMP_NUM_THREADS} threads"

########################################################################
# cleanup
cd $SLURM_SUBMIT_DIR
echo $SLURM_SUBMIT_DIR
########################################################################
# run the binary
echo
echo "in rundir: $(pwd)"
echo
ls -lL $BINARY
rm -f READY
echo
ls -lL ../input
echo
echo "###CORE: Job start: $(date)"
echo
echo "Replacing namelist for Leonardo"
echo
rm namelist
cp /leonardo_work/DE360_GLORI/smr_prod/scenarios/scenario_2/lam/namelist_kenda namelist
export MPIRUN_OPTIONS="--bind-to core --map-by core -report-bindings"
startexe="mpirun -n ${SLURM_NTASKS} ${BINARY}"
echo $startexe
mpirun -v -n ${SLURM_NTASKS} ${BINARY}
rc=$?
echo ${rc}
echo "------------------------------------------------------------------------"
echo
echo "###CORE: Job end:   $(date)"
echo
########################################################################
# delete empty files
find -size 0 -delete
# check return code
if [ $rc -ne 0 ]; then
    echo "mpirun failed: rc=$rc" 
    echo "mpirun failed: rc=$rc" >&2
    exit $rc
fi
date > READY
